""" version which can be consumed from within the module """
VERSION_STR = "0.0.6"
DESCRIPTION = "Pyfoldercheck will apply a set of checks on files in a folder"
APP_NAME = "pyfoldercheck"
LOGGER_NAME = "pyfoldercheck"
